name: bown
favicon: null
layout_spectrum: 0.34548
typography_spectrum: 0.958316563628614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#395b77'
    - '#fcfdf7'
    - '#99a1ab'
    - '#a66b31'
  brandStrength: 0.4375
  lightness: 0.8174537417944521
  saturation: 0.22438065288588405
  rhythmicContrast: 0.33267730521038175
purpose: []
