name: bown
favicon: null
layout_spectrum: 0.030317838536575437
typography_spectrum: 0.958316563628614
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2616861911956221
  lightness: 0.8174537417944521
  saturation: 0.22438065288588405
  rhythmicContrast: 0.33267730521038175
purpose: []
