name: Bown
favicon: null
layout_spectrum: 0.24281
typography_spectrum: 0.50338
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#395b77'
    - '#fcfdf7'
    - '#99a1ab'
    - '#a66b31'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.9404255
  rhythmicContrast: 0.3957447
purpose: []
